name: manage-azure-policy-77000db9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'azpolicy/policies/Configure_App_Service_app_slots_to_disable_local_authentication_for_FTP_deployments_f493116f-3b7f-4ab3-bf80-0c2af35e46c2/**'
#      - .github/workflows/manage-azure-policy-77000db9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_77000db9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          azpolicy/policies/Configure_App_Service_app_slots_to_disable_local_authentication_for_FTP_deployments_f493116f-3b7f-4ab3-bf80-0c2af35e46c2/**
